platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared
    pod 'Marshal'
    pod 'KeychainAccess'
    pod 'BonMot', :git => 'https://github.com/Raizlabs/BonMot'
    pod 'Alamofire'
    pod 'Anchorage', :git => 'https://github.com/Raizlabs/Anchorage'
    pod 'Swiftilities', :git => 'https://github.com/Raizlabs/Swiftilities'
end

target 'DemoCI' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'GoogleAnalytics',   '~>3.0'
  
  pod 'SimulatorStatusMagic', :configurations => ['Debug']

  target 'DemoCITests' do
    pod 'OHHTTPStubs/Swift'
  end

  shared()
end

target 'Services' do
    shared()
end

pod 'SwiftGen'
pod 'Sourcery', '~> 0.12.0'
pod 'SwiftLint'
